name: CI configure
on:
  push:
    branches: [main]
jobs:
  github-ci-actions:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.10]
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: installing node_modules
        run: npm install
      - name: building project
        run: npm run build:prod
      - name: running eslint
        run: npm run lint
      - name: running tests
        run: npm run test:prod
      - run: echo "This job's status is ${{ job.status }}."
